export default {
    DEPOSIT: 'gameLogic.deposit',
    WITHDRAWAL: 'gameLogic.withdrawal',
    WIN: 'gameLogic.win',
    REFUND: 'gameLogic.refund',
    GET_BALANCE: 'gameLogic.getBalance',
    CREATE_ROOM: 'gameLogic.createRoom',
    JOIN_ROOM: 'gameLogic.joinRoom',
    GAME: 'gameLogic.game',
    GAME_OVER: 'gameLogic.gameOver',
    DELETE_PLAYER_ROOM_ID: 'gameLogic.deletePlayerRoomId',
    DELETE_ROOM: 'gameLogic.deleteRoom',
    GET_START_INSTRUCTION: 'gameLogic.getStartInstruction',
    CHANGE_LANGUAGE: 'gameLogic.changeLanguage',
    UNKNOWN_CONFERENCE_MESSAGE_HANDLING: 'gameLogic.unknownConferenceMessageHandling',
    WARN: 'gameLogic.warn',
    HANDLING_PLAYERS_WARNING: 'gameLogic.handlingPlayersWarning',
    GET_ROOM_LIST: 'gameLogic.getRoomList',
    TIMER_TRIGGER: 'gameLogic.timerTrigger',
    HELP: 'gameLogic.help',
    RAKE_TRANSFER: 'gameLogic.rakeTransfer',
};
